### ISSUE TITLE
Laravel 7.x support

### ISSUE THREAD

**Issue by gregorip02** [nebulapackage/nebula#19]
What do you think about adding support to Laravel 7.x? I have several projects in which I want to test your package.

**Comment by Larsklopstra** [comment]
Most of the logic relies on `x-dynamic-component` which is a new feature in Laravel 8.x. I think it'd be better if we only support all releases starting from Laravel 8.x. Most users will start using Laravel 8.x by the time Nebula 1.0.0 is released.

**Comment by gregorip02** [comment]
Ok now I have another good reason to update my projects 😅. Thanks
