### ISSUE TITLE
Refactor to livewire

### ISSUE THREAD

**Issue by Larsklopstra** [nebulapackage/nebula#25]

**Comment by ryangjchandler** [comment]
One suggestion on this is to not make the whole thing a Livewire based app, just make smaller Livewire components so that people aren't completely tied into using Livewire.

**Comment by Larsklopstra** [comment]
Don't worry, fields, metrics and other features will remain easy and simple to use as they don't require Livewire :)

**Comment by ryangjchandler** [comment]
> Don't worry, fields, metrics and other features will remain easy and simple to use as they don't require Livewire :)

Very nice. I imagine Livewire will be used for tables, filtering, etc?

**Comment by Larsklopstra** [comment]
> > Don't worry, fields, metrics and other features will remain easy and simple to use as they don't require Livewire :)
> 
> Very nice. I imagine Livewire will be used for tables, filtering, etc?

Exactly!

**Comment by Wulfheart** [comment]
Keep in mind that currently livewire doesn't support multiple paginations on one page.

https://github.com/livewire/livewire/issues/1209

**Comment by Larsklopstra** [comment]
Hmm... I think the tables should be self contained

**Comment by Wulfheart** [comment]
However if you have multiple tables on one page (e.g. multiple relations) this can be an issue. However I think this is going to get fixed.

**Comment by Larsklopstra** [comment]
Not sure if I still want to go down this path. Once Nebula is more stable I'll reconsider it. Relational fields are more urgent.
