### ISSUE TITLE
Laravel Jetstream / Fortify

### ISSUE THREAD

**Issue by relaypilot** [nebulapackage/nebula#26]
Is it possible to pull this package into a fresh Laravel Jetstream application, or is there gonna be conflicts with the authorization process? Using the users/teams features from Jetstream hand to hand with Nebula would be great!

**Comment by MrGKanev** [comment]
@relaypilot we are using it on a Jetstream application as well. It works fine but you need to do the process "by hand". There isn't a roles/permissions type of login but you can make it yourself. It will be great if it is implemented as you mentioned.
