### ISSUE TITLE
Field creation

### ISSUE THREAD

**Issue by Larsklopstra** [nebulapackage/nebula#31]
Refactor the `make()` method so it takes the label first and accepts a column:

`Input::make('Name', 'column')`

`name` is required and the `column` is optional

**Comment by bitasterisk** [comment]
is make() method already there ? i need to understand it correctly. and i am interested to work on this issue.

**Comment by Larsklopstra** [comment]
> is make() method already there ? i need to understand it correctly. and i am interested to work on this issue.

It's already there, check out `NebulaField.php`

**Comment by bitasterisk** [comment]
master branch right? i don't see any.
https://github.com/nebulapackage/nebula/find/master

**Comment by tobischulz** [comment]
I did created a PR for this https://github.com/nebulapackage/nebula/pull/34
