### ISSUE TITLE
Clean up the service provider

### ISSUE THREAD

**Issue by Larsklopstra** [nebulapackage/nebula#32]
The service provider contains too much logic, consider separating the route binding

**Comment by johnnyfekete** [comment]
Hi @Larsklopstra I'd gladly do this PR

Do you have any preference, where to put the bindings? Maybe a new file, something like `src/Http/RoutesResolver.php`?

Then it could have the 3 methods for the route bindings, and maybe the `mapWebRoutes` as well.

Or if you were thinking something totally different, tell me, I'd be glad to do it 🙂

**Comment by Larsklopstra** [comment]
@johnnyfekete that sounds like a plan :) Perhaps even 

```
LarsKlopstra\Nebula\Http\RouteResolvers

- ResourceResolver.php
- ItemResolver.php
```
