### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by vitormicillo** [nebulapackage/nebula#57]
Hi, all features is compatible with Laravel 8 ?
I tried to create a new project, following all the steps in the documentation, but when the user's CRUD is accessed it returns the error:
![image](https://user-images.githubusercontent.com/1921806/104619347-aabbb700-5685-11eb-9c52-bbbac4a0d120.png)

and when I try to insert a new record:
![image](https://user-images.githubusercontent.com/1921806/104619470-cf179380-5685-11eb-90ad-3ec4d2b18003.png)

Thanks in advance

**Comment by vitormicillo** [comment]
I believe that I managed to solve the problem, I take a look at the source code files and the names are declared differently.
So I modified the inclusion of the reference at the top of the file, being as follows:

`use Larsklopstra\Nebula\Fields\Input as InputField;`

If anyone else had problems with this

**Comment by Larsklopstra** [comment]
Great!
